name: bfastui
description: BFast Ui manage sdk for flutter
version: 1.0.0-beta.3
author: Fahamu Tech
homepage: https://github.com/fahamutech/bfast-ui-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: