name: bfastui
description: easy and fast ways to manage  ui
version: 1.3.0
homepage: https://github.com/fahamutech/bfast-ui-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  builders: ^2.0.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter

flutter:
